version: "3"
services:
  # Development
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3009:3000
    tty: true
    command: npm run watch
  # Production
  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile-prod
  #   volumes:
  #     - ./server:/usr/src/app
  #   working_dir: /usr/src/app
  #   ports:
  #     - 3000:3000
  #   tty: true
  db:
    image: postgres:11.2
    ports:
      - 3010:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db:/home/db_dumps
    working_dir: /home/db_dumps
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=guest_list
volumes:
  dbdata:
    driver: local
