version: "3"
services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3009:3000
    tty: true
    command: npm run watch
  db:
    image: mongo
    ports:
      - 3010:27017
    volumes:
      - dbdata:/data/db
      - ./db:/home/db
    working_dir: /home/db
    environment:
      - TZ=America/Sao_Paulo
volumes:
  dbdata:
    driver: local
