version: "3"
services:
  # Development
  # server:
  # build:
  #   context: ./server
  #   dockerfile: Dockerfile-dev
  #   volumes:
  #     - ./server:/usr/src/app
  #   working_dir: /usr/src/app
  #   ports:
  #     - 3009:3000
  #   tty: true
  #   command: npm run watch
  # Production
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-prod
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    tty: true
  db:
    image: mongo:4
    ports:
      - 3010:27017
    volumes:
      - dbdata:/data/db
      - ./db:/home/db
    working_dir: /home/db
    environment:
      - TZ=America/Sao_Paulo
volumes:
  dbdata:
    driver: local
